fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'https://github.com/puppetlabs/puppetlabs-concat.git'
    apt: 'https://github.com/puppetlabs/puppetlabs-apt.git'
    translate: 'https://github.com/puppetlabs/puppetlabs-translate.git'
    firewall: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
    systemd: 'https://github.com/voxpupuli/puppet-systemd.git'
    mount_core: 'https://github.com/puppetlabs/puppetlabs-mount_core.git'
    yumrepo_core: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
